### PR TITLE
Fix model collection

### PR DESCRIPTION
**Pull request by rustamwin**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | yes/no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | #15

### CODE REVIEW

**Comment by rustamwin** [comment]
@cebe whitespaces reverted

**Comment by cebe** [comment]
Hm... a Collection is considered to be read-only by design. Calling methods on it should only return a new collection that represents the change.

**Comment by rustamwin** [comment]
>Collection is considered to be read-only by design

is it `parent::__construct($this->_models)` ?

**Comment by cebe** [comment]
that would probably work but it would be a hack. need to check the overall design to see how we could solve it.

**Comment by rustamwin** [comment]
@cebe ?

**Comment by matiosfree** [comment]
is there any chance to have it merged? the package is not working for 2 years

**Comment by samdark** [comment]
Let's have it.

**Pull request merged**
