### PR TITLE
Collection: use ArrayAccessTrait, clone objects

### PR DESCRIPTION
**Pull request by WinterSilence**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | yes/no
| Tests pass?   | yes
| Fixed issues  |

### CODE REVIEW

**Comment by WinterSilence** [comment]
@bizley list of BC please

**Comment by bizley** [comment]
Removing interfaces, removing default `$data` value from constructor.

**Comment by WinterSilence** [comment]
@bizley 
> Removing interfaces

my fail - fixed

> removing default $data

it's not BC, - default value in this case is unusable

**Comment by bizley** [comment]
True ;)

**Pull request merged**
